apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-stack.fullname" . }}-app
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mcpContextForge.service.type }}
  selector:
    app: {{ include "mcp-stack.fullname" . }}-app
  ports:
    - port: {{ .Values.mcpContextForge.service.port }}
      targetPort: {{ .Values.mcpContextForge.containerPort }}
      protocol: TCP
