# Inherit config from base
INHERIT: ./base.yml

# Project Information
site_name: "MCP Context Forge - Model Context Protocol Gateway"
site_url: "https://pages.github.com/ibm/mcp-context-forge/"
site_description: "MCP Gateway Documentation"
site_author: "Mihai Criveti"

# Repository Information
repo_name: 'ibm/mcp-context-forge'
repo_url: 'https://github.com/ibm/mcp-context-forge'

# Copyright
copyright: Apache 2.0

# Theme settings
theme:
  language: en
  features:
    - announce.dismiss        # Button to dismiss the current temporary announcement
    - content.action.edit
    - content.action.feedback
    # - content.action.view
    - content.code.annotate   # Attach arbitrary content to specific sections of code blocks by adding numeric markers
    - content.code.copy       # Button to allow the user to copy a code block's contents to the clipboard
    # - content.tabs.link
    # - navigation.expand     # Expand left sidebar by default
    - navigation.indexes      # Attach documents to sections, useful for providing overview pages
    - navigation.instant      # Single page instant refresh
    # - navigation.sections   # Top level tabs rendered in sidebar
    - navigation.tabs         # Navigation tabs across top. Comment this out to have navigation on the left
    - navigation.tabs.sticky  # Tab always displayed
    - navigation.top          # Back-to-top button. Rendered centered and just below the header
    - navigation.tracking     # URL updated with active anchor
    - search.share
    - search.suggest
    - toc.integrate           # Integrate page TOC in left sidebar - wider page
  icon:
    edit: 'material/pencil-outline'

markdown_extensions:
  pymdownx.magiclink:
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: false
      social_url_shorthand: true
      user: ibm
      repo: ibm/mcp-context-forge
  toc:
      permalink: true
      toc_depth: 3

plugins:
  # Built-in blog plugin - see https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  # blog:
  #     blog_dir: "blog"
  #     pagination_per_page: 5
  #     post_date_format: full
  #     post_url_date_format: yyyy/MM/dd
  # Allow Tags on the pages - see https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # tags:
  #     tags_file: tags.md
  # Configure the PDF export plugin - see https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
  with-pdf: # This creates a single PDF document for the whole site
      author: Mihai Criveti
      copyright: Copyright &copy; Apache 2.0
      cover: true
      back_cover: false
      #
      cover_title: MCP Context Forge - MCP Gateway
      cover_subtitle: MCP Gateway Documentation
      cover_logo: 'theme/logo.png'
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Contents
      # heading_shift: false
      toc_level: 2
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
          - 'blog'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      # render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: ./pdf/mcpgateway-docs.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      debug_html: true
      #show_anchors: true
      verbose: false
